import { NFT_IMAGES } from "./assets/images";

export interface NFTItem {
  id: string;
  name: string;
  region: string;
  outfit: string;
  rarity: "Common" | "Rare" | "Epic" | "Legendary" | "Mythic" | "Divine";
  image: string;
  lore: string;
  ability: string;
  rarityReason: string;
  price: string;
  supply: string;
  culturalMeaning: string;
  spirit: string;
  element: "Earth" | "Water" | "Fire" | "Air" | "Void" | "Light";
  island: "Sumatra" | "Java" | "Kalimantan" | "Sulawesi" | "Papua" | "Nusa Tenggara" | "Maluku";
  openseaUrl: string;
}

export const OPENSEA_BASE_URL = "https://opensea.io/assets/ethereum";
export const CONTRACT_ADDRESS = "0x5678...4321"; // Placeholder contract
export const COLLECTION_SLUG = "nusantara-eterna-genesis";

export const getOpenSeaUrl = (id: string) => `${OPENSEA_BASE_URL}/${CONTRACT_ADDRESS}/${id}`;
export const getCollectionUrl = () => `https://opensea.io/collection/${COLLECTION_SLUG}`;

export const NFT_COLLECTION: NFTItem[] = [
  // Sumatra
  {
    id: "1",
    name: "Royal Raccoon",
    region: "Aceh",
    outfit: "Ulee Balang",
    rarity: "Rare",
    image: `https://picsum.photos/seed/aceh-ulee/800/1000`,
    lore: "The official presence of the Northern tip. Worn by the nobility, it radiates high authority with its deep black and gold accents.",
    ability: "Sultan's Protocol: Commands respect in any diplomatic encounter.",
    rarityReason: "Worn by the elite of the Aceh Sultanate.",
    price: "1.8",
    supply: "50/50",
    culturalMeaning: "Represents the historical sovereignty and strict adherence to official protocols.",
    spirit: "Northern Regent",
    element: "Void",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("1")
  },
  {
    id: "2",
    name: "Royal Raccoon",
    region: "Gayo",
    outfit: "Kerawang Gayo",
    rarity: "Epic",
    image: `https://picsum.photos/seed/gayo-kerawang/800/1000`,
    lore: "A costume woven with deep philosophical motifs. Every embroidered thread tells a story of the highland's cultural strength.",
    ability: "Woven Wisdom: Deciphers ancient patterns to reveal hidden truths.",
    rarityReason: "Highly complex embroidery requiring master craftsmanship.",
    price: "3.5",
    supply: "25/25",
    culturalMeaning: "Reflects the identity and community spirit of the Gayo people.",
    spirit: "Highland Weaver",
    element: "Earth",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("2")
  },
  {
    id: "3",
    name: "Royal Raccoon",
    region: "Batak Toba",
    outfit: "Ulos Ragidup",
    rarity: "Epic",
    image: `https://picsum.photos/seed/batak-ragidup/800/1000`,
    lore: "The most sacred of all Ulos. It is the 'Fabric of Life,' essential for the most important rituals of birth and union.",
    ability: "Vitality Pulse: Grants regenerative energy to those within its aura.",
    rarityReason: "The highest grade of sacred textile in Batak culture.",
    price: "4.2",
    supply: "20/20",
    culturalMeaning: "Symbolizes the cycle of life and the blessing of ancestors.",
    spirit: "Life Weaver",
    element: "Light",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("3")
  },
  {
    id: "4",
    name: "Royal Raccoon",
    region: "Batak Karo",
    outfit: "Uis Gara",
    rarity: "Rare",
    image: `https://picsum.photos/seed/karo-uisgara/800/1000`,
    lore: "The 'Red Cloth' that defines the Karo spirit. Its vibrant hue signals a strong social identity and ancestral pride.",
    ability: "Crimson Shield: Absorbs negative intent and converts it into pure static energy.",
    rarityReason: "A primary symbol of social standing in the Karo highlands.",
    price: "2.0",
    supply: "40/40",
    culturalMeaning: "Represents the warmth of the community and the fire of identity.",
    spirit: "Mountain Flame",
    element: "Fire",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("4")
  },
  {
    id: "5",
    name: "Royal Raccoon",
    region: "Nias",
    outfit: "Baru Oholu",
    rarity: "Legendary",
    image: `https://picsum.photos/seed/nias-oholu/800/1000`,
    lore: "The warrior's armor of the stone-jumping knights. Forged for tradition and battle, it is as heavy as history but agile as a hunter.",
    ability: "Stone Leap: Allows for massive bursts of vertical movement and gravity defiance.",
    rarityReason: "Reserved for the masters of the Nias combat arts.",
    price: "8.5",
    supply: "10/10",
    culturalMeaning: "Symbolizes maturity, strength, and the overcoming of great obstacles.",
    spirit: "Stone Hunter",
    element: "Earth",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("5")
  },
  {
    id: "6",
    name: "Royal Raccoon",
    region: "Minangkabau",
    outfit: "Bundo Kanduang",
    rarity: "Epic",
    image: `https://picsum.photos/seed/minang-bundo/800/1000`,
    lore: "The crown of the matriarch. With its towering Suntiang, it represents the wise pillar of the Minang society.",
    ability: "Matriarch's Insight: Can perceive the hidden intentions of any being.",
    rarityReason: "Intricate headgear and gold-threaded silk representing royal bloodlines.",
    price: "5.0",
    supply: "15/15",
    culturalMeaning: "Honors the central power of women in the matriarchal lineage.",
    spirit: "Pillar of Wisdom",
    element: "Earth",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("6")
  },
  {
    id: "7",
    name: "Royal Raccoon",
    region: "Mentawai",
    outfit: "Kabit",
    rarity: "Legendary",
    image: `https://picsum.photos/seed/mentawai-kabit/800/1000`,
    lore: "A minimalist connection to the natural world. Far more than a garment, it is a canvas for sacred tattoos and an extension of the forest floor.",
    ability: "Primal Sync: Moves with total silence and total camouflage in natural environments.",
    rarityReason: "Deep connection to the nearly-lost arts of the forest dwellers.",
    price: "9.0",
    supply: "5/5",
    culturalMeaning: "Reflects the harmony between man, spirit, and nature.",
    spirit: "Forest Ghost",
    element: "Water",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("7")
  },
  {
    id: "8",
    name: "Royal Raccoon",
    region: "Melayu Riau",
    outfit: "Teluk Belanga",
    rarity: "Common",
    image: `https://picsum.photos/seed/riau-teluk/800/1000`,
    lore: "The versatile standard of the Malay coast. Elegant yet practical, it transitions from humble gathering to royal court with ease.",
    ability: "Fluid Motion: Increases base movement speed and reaction time.",
    rarityReason: "The most widely recognized and accessible form of Malay formal wear.",
    price: "0.5",
    supply: "100/100",
    culturalMeaning: "Embodies the polite and graceful nature of coastal societies.",
    spirit: "Coastal Guard",
    element: "Water",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("8")
  },
  {
    id: "9",
    name: "Royal Raccoon",
    region: "Palembang",
    outfit: "Aesan Gede",
    rarity: "Epic",
    image: `https://picsum.photos/seed/palembang-aesan/800/1000`,
    lore: "The 'Grand Wedding' attire of the Sriwijaya descendants. Dripping in gold and refined silk, it is the peak of Musi river nobility.",
    ability: "Golden Radiance: Emits a light that briefly stuns and disorients attackers.",
    rarityReason: "Requires immense historical knowledge to craft the authentic gold ornaments.",
    price: "4.5",
    supply: "25/25",
    culturalMeaning: "Captures the opulence of the golden age of the maritime empire.",
    spirit: "River Noble",
    element: "Light",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("9")
  },
  {
    id: "10",
    name: "Royal Raccoon",
    region: "Lampung Pepadun",
    outfit: "Adat Pepadun",
    rarity: "Epic",
    image: `https://picsum.photos/seed/lampung-pepadun/800/1000`,
    lore: "The Siger crown is the throne of the mind. This costume defines the high status and rich traditions of the Pepadun plains.",
    ability: "Siger's Call: Projects a powerful voice that can be heard across entire territories.",
    rarityReason: "Unique headgear design found nowhere else in the world.",
    price: "4.2",
    supply: "20/20",
    culturalMeaning: "Symbolizes women's dignity and the strength of the southern gateway.",
    spirit: "Gate Guardian",
    element: "Light",
    island: "Sumatra",
    openseaUrl: getOpenSeaUrl("10")
  },

  // Jawa
  {
    id: "11",
    name: "Royal Raccoon",
    region: "Baduy Dalam",
    outfit: "Pakaian Putih",
    rarity: "Legendary",
    image: `https://picsum.photos/seed/baduy-dalam/800/1000`,
    lore: "The ultimate vow of simplicity. Pure white, woven by hand, it is the armor of a soul that has rejected the chaos of the modern world.",
    ability: "Inner Peace: Completely nullifies all mental debuffs and psychic attacks.",
    rarityReason: "Deeply sacred and rarely shared with the outside world.",
    price: "12.0",
    supply: "3/3",
    culturalMeaning: "Represents the total commitment to ancestral laws and purity of thought.",
    spirit: "Silent Sage",
    element: "Void",
    island: "Java",
    openseaUrl: getOpenSeaUrl("11")
  },
  {
    id: "12",
    name: "Royal Raccoon",
    region: "Baduy Luar",
    outfit: "Pakaian Hitam",
    rarity: "Rare",
    image: `https://picsum.photos/seed/baduy-luar/800/1000`,
    lore: "The bridge between two worlds. The black attire signifies a protector of the inner sanctuary who interacts with the shifting currents of outer society.",
    ability: "Fading Shadow: Can blink between the physical and spirit planes momentarily.",
    rarityReason: "The secondary tier of the sacred Banten forest guardians.",
    price: "2.5",
    supply: "30/30",
    culturalMeaning: "Symbolizes the necessary link between tradition and change.",
    spirit: "Border Walker",
    element: "Void",
    island: "Java",
    openseaUrl: getOpenSeaUrl("12")
  },
  {
    id: "13",
    name: "Royal Raccoon",
    region: "Betawi",
    outfit: "Kebaya Encim",
    rarity: "Common",
    image: `https://picsum.photos/seed/betawi-encim/800/1000`,
    lore: "A beautiful fusion of Malay, Chinese, and native Betawi aesthetics. It carries the vibrant energy of the bustling capital city.",
    ability: "Market Whiz: Automatically identifies the most efficient trade routes and prices.",
    rarityReason: "A popular and beloved symbol of Jakarta's heritage.",
    price: "0.8",
    supply: "100/100",
    culturalMeaning: "Reflects the multi-ethnic roots and adaptability of Betawi culture.",
    spirit: "City Scout",
    element: "Light",
    island: "Java",
    openseaUrl: getOpenSeaUrl("13")
  },
  {
    id: "14",
    name: "Royal Raccoon",
    region: "Sunda",
    outfit: "Kebaya Sunda",
    rarity: "Common",
    image: `https://picsum.photos/seed/sunda-kebaya/800/1000`,
    lore: "Graceful and flexible, much like the Sundanese lifestyle. It is the garment of a thousand celebrations and forest gatherings.",
    ability: "Forest Echo: Can communicate through the whispering of the mountain winds.",
    rarityReason: "Widely used across West Java for various cultural events.",
    price: "0.8",
    supply: "100/100",
    culturalMeaning: "Represents the polite and nature-loving soul of the Parahyangan highlands.",
    spirit: "Mountain Whisper",
    element: "Air",
    island: "Java",
    openseaUrl: getOpenSeaUrl("14")
  },
  {
    id: "15",
    name: "Royal Raccoon",
    region: "Jawa Tengah",
    outfit: "Jawi Jangkep",
    rarity: "Epic",
    image: `https://picsum.photos/seed/jawa-jangkep/800/1000`,
    lore: "The formal standard of the courts. Every fold of the cloth and placement of the Kris is a lesson in balance and self-restraint.",
    ability: "Court Decree: Can briefly 'pause' an opponent's turn by imposing royal etiquette.",
    rarityReason: "Complicated dressing process and strict adherence to keraton styles.",
    price: "4.8",
    supply: "20/20",
    culturalMeaning: "Symbolizes the pursuit of 'Tepa Selira'—harmony and empathy.",
    spirit: "Court Executor",
    element: "Earth",
    island: "Java",
    openseaUrl: getOpenSeaUrl("15")
  },
  {
    id: "16",
    name: "Royal Raccoon",
    region: "Yogyakarta",
    outfit: "Surjan",
    rarity: "Rare",
    image: `https://picsum.photos/seed/yogya-surjan/800/1000`,
    lore: "The 'Garment of Light.' Its striped pattern is a mnemonic for the pillars of faith, keeping the wearer grounded in spiritual reality.",
    ability: "Faith's Piercing: Can see through any illusion or deceptive fog.",
    rarityReason: "Specific spiritual philosophical design unique to the DIY region.",
    price: "2.2",
    supply: "40/40",
    culturalMeaning: "Represents the integration of faith and daily life.",
    spirit: "Faith Seer",
    element: "Light",
    island: "Java",
    openseaUrl: getOpenSeaUrl("16")
  },
  {
    id: "17",
    name: "Royal Raccoon",
    region: "Madura",
    outfit: "Pesa’an",
    rarity: "Rare",
    image: `https://picsum.photos/seed/madura-pesaan/800/1000`,
    lore: "Red and white stripes signify a bold heart and a pure spirit. It is the attire of a sea-faring survivor who fears no storm.",
    ability: "Salt Gale: Summons a dry, salt-laden wind that erodes obstacles.",
    rarityReason: "Iconic and unmistakable identity of the Madurese character.",
    price: "1.9",
    supply: "50/50",
    culturalMeaning: "Symbolizes courage, work ethic, and uncompromising loyalty.",
    spirit: "Salt-Wind Mariner",
    element: "Air",
    island: "Java",
    openseaUrl: getOpenSeaUrl("17")
  },
  {
    id: "18",
    name: "Royal Raccoon",
    region: "Tengger",
    outfit: "Adat Tengger",
    rarity: "Epic",
    image: `https://picsum.photos/seed/tengger-adat/800/1000`,
    lore: "Reserved for the rites of the great ash-mountain. It is insulated against the volcanic cold and the swirling mists of Bromo.",
    ability: "Ash Step: Allows the wearer to walk safely on lava or extreme heat surfaces.",
    rarityReason: "Used primarily in the sacred Kasada ceremony at the volcanic crater.",
    price: "5.5",
    supply: "15/15",
    culturalMeaning: "Reflects the devotion to the ancestors of the volcanic peaks.",
    spirit: "Flame Priest",
    element: "Fire",
    island: "Java",
    openseaUrl: getOpenSeaUrl("18")
  },

  // Bali & Nusa Tenggara
  {
    id: "19",
    name: "Royal Raccoon",
    region: "Bali Aga",
    outfit: "Payas Agung",
    rarity: "Epic",
    image: `https://picsum.photos/seed/baliaga-payas/800/1000`,
    lore: "A complex architectural marvel made of gold and silk. It is the peak of Balinese ceremonial aesthetics, reserved for the highest gods.",
    ability: "Divine Mirror: Reflects incoming energy projectiles back to their source.",
    rarityReason: "Extreme complexity and high concentration of ceremonial gold.",
    price: "7.0",
    supply: "10/10",
    culturalMeaning: "The physical embodiment of the triad of gods—Brahma, Vishnu, and Shiva.",
    spirit: "Celestial Dancer",
    element: "Light",
    island: "Java",
    openseaUrl: getOpenSeaUrl("19")
  },
  {
    id: "20",
    name: "Royal Raccoon",
    region: "Sasak",
    outfit: "Lambung",
    rarity: "Rare",
    image: `https://picsum.photos/seed/sasak-lambung/800/1000`,
    lore: "The beauty of simplicity. This costume represents the grounded nature of the Lombok highlands and the steady pulse of a quiet life.",
    ability: "Highland Grace: Grants a passive evasion bonus to all nearby allies.",
    rarityReason: "Elegant craftsmanship using traditional Lombok weaving techniques.",
    price: "2.8",
    supply: "35/35",
    culturalMeaning: "Represents the humility and steady labor of the Sasak women.",
    spirit: "Highland Grace",
    element: "Earth",
    island: "Nusa Tenggara",
    openseaUrl: getOpenSeaUrl("20")
  },
  {
    id: "21",
    name: "Royal Raccoon",
    region: "Bima",
    outfit: "Rimpu",
    rarity: "Epic",
    image: `https://picsum.photos/seed/bima-rimpu/800/1000`,
    lore: "A cloak of mystery and devotion. It shields the wearer from the scorching sun and the gaze of the world, preserving a high spiritual value.",
    ability: "Silent Veil: Makes the wearer undetectable by radar or sonar systems.",
    rarityReason: "A unique religious-cultural fusion specific to the Mbojo tribe.",
    price: "5.2",
    supply: "18/18",
    culturalMeaning: "Symbolizes modesty, religion, and the protection of the inner self.",
    spirit: "Silent Devotee",
    element: "Air",
    island: "Nusa Tenggara",
    openseaUrl: getOpenSeaUrl("21")
  },
  {
    id: "22",
    name: "Royal Raccoon",
    region: "Sumba",
    outfit: "Tenun Ikat Sumba",
    rarity: "Epic",
    image: `https://picsum.photos/seed/sumba-tenun/800/1000`,
    lore: "Woven with motifs of legendary horses and ancient spirits. Each ikat is a spiritual contract between the weaver and the ancestors.",
    ability: "Ancestral Steed: Summons an ethereal horse and increases travel speed tenfold.",
    rarityReason: "Natural dyeing processes that can take years to complete.",
    price: "6.0",
    supply: "12/12",
    culturalMeaning: "Reflects the Marapu belief system where animals are spirit messengers.",
    spirit: "Spirit Rider",
    element: "Fire",
    island: "Nusa Tenggara",
    openseaUrl: getOpenSeaUrl("22")
  },
  {
    id: "23",
    name: "Royal Raccoon",
    region: "Rote",
    outfit: "Ti’i Langga",
    rarity: "Rare",
    image: `https://picsum.photos/seed/rote-tiilangga/800/1000`,
    lore: "The iconic antlered hat of the southern mariners. It is said that the horns catch the whispers of the ocean to guide the sailors home.",
    ability: "Current Catcher: Can command the direction of small ocean currents.",
    rarityReason: "Specific intricate palm-leaf weaving used only in the Rote island.",
    price: "2.4",
    supply: "45/45",
    culturalMeaning: "The symbol of a Rote man's maturity and his bond with the sea.",
    spirit: "Ocean Horn",
    element: "Water",
    island: "Nusa Tenggara",
    openseaUrl: getOpenSeaUrl("23")
  },
  {
    id: "24",
    name: "Royal Raccoon",
    region: "Timor",
    outfit: "Amarasi",
    rarity: "Rare",
    image: `https://picsum.photos/seed/timor-amarasi/800/1000`,
    lore: "A heavy, complex weave that indicates high status. It carries the weight of many generations of family lineage within its threads.",
    ability: "Legacy Anchor: Stabilizes any area, preventing terrain deformation or shaking.",
    rarityReason: "Royal weaving patterns reserved for family elders.",
    price: "3.0",
    supply: "30/30",
    culturalMeaning: "Symbolizes family ties and the stability of the clan.",
    spirit: "Clan Anchor",
    element: "Earth",
    island: "Nusa Tenggara",
    openseaUrl: getOpenSeaUrl("24")
  },

  // Kalimantan
  {
    id: "25",
    name: "Royal Raccoon",
    region: "Dayak Iban",
    outfit: "King Baba",
    rarity: "Epic",
    image: `https://picsum.photos/seed/dayak-kingbaba/800/1000`,
    lore: "Made from the feathers of the Hornbill and the bark of the Upas tree. It is the costume of a jungle monarch who knows every secret of the canopy.",
    ability: "Enggang's Eye: Grants a bird's eye view persistent map of the surroundings.",
    rarityReason: "Use of sacred and rare forest materials.",
    price: "6.5",
    supply: "15/15",
    culturalMeaning: "Represents bravery, freedom, and the majesty of the Hornbill bird.",
    spirit: "Jungle Monarch",
    element: "Air",
    island: "Kalimantan",
    openseaUrl: getOpenSeaUrl("25")
  },
  {
    id: "26",
    name: "Royal Raccoon",
    region: "Dayak Ngaju",
    outfit: "Sangkarut",
    rarity: "Epic",
    image: `https://picsum.photos/seed/dayak-sangkarut/800/1000`,
    lore: "A vest of protection used for both spiritual rites and the ancient ways of protection. It is toughened by ritual and nature's own materials.",
    ability: "Spirit Bulwark: Creates a short-range barrier that deflects physical impacts.",
    rarityReason: "Ritually consecrated for protection of the village leaders.",
    price: "5.8",
    supply: "20/20",
    culturalMeaning: "Symbolizes the fortitude and spiritual preparedness of the warrior.",
    spirit: "Village Bulwark",
    element: "Fire",
    island: "Kalimantan",
    openseaUrl: getOpenSeaUrl("26")
  },
  {
    id: "27",
    name: "Royal Raccoon",
    region: "Dayak Kenyah",
    outfit: "Ta’a & Sapei Sapaq",
    rarity: "Epic",
    image: `https://picsum.photos/seed/dayak-taasapei/800/1000`,
    lore: "Intricate beadwork and motifs of the swirling sun and river spirits. It is a harmonious blend of many forest tribes' highest arts.",
    ability: "Harmonic Pulse: Regenerates health for all nearby allies as long as they are moving.",
    rarityReason: "Extreme bead count and master-level embroidery.",
    price: "6.2",
    supply: "15/15",
    culturalMeaning: "Reflects the unity between the people and the vibrant life of the Borneo rivers.",
    spirit: "River Soul",
    element: "Water",
    island: "Kalimantan",
    openseaUrl: getOpenSeaUrl("27")
  },
  {
    id: "28",
    name: "Royal Raccoon",
    region: "Banjar",
    outfit: "Bagajah Gamuling",
    rarity: "Rare",
    image: `https://picsum.photos/seed/banjar-bagajah/800/1000`,
    lore: "The attire of the Banjar courts. Elegant and structured, it reflects the history of the river kingdoms and the trade with distant lands.",
    ability: "Trading Wind: Increases gains from any economic transactions.",
    rarityReason: "Historic courtly design with precise silk weaving.",
    price: "3.2",
    supply: "30/30",
    culturalMeaning: "Represents the royal heritage and maritime prosperity of Banjarmasin.",
    spirit: "River Merchant",
    element: "Water",
    island: "Kalimantan",
    openseaUrl: getOpenSeaUrl("28")
  },
  {
    id: "29",
    name: "Royal Raccoon",
    region: "Kutai",
    outfit: "Kustin",
    rarity: "Rare",
    image: `https://picsum.photos/seed/kutai-kustin/800/1000`,
    lore: "Worn by the nobility of the oldest kingdom in Nusantara. It carries the weight of a lineage that stretches back to the dawn of recorded history.",
    ability: "Ancient Gaze: Reveals historical data and lore about any item or location.",
    rarityReason: "Royal attire from the historically significant Kutai Sultanate.",
    price: "3.5",
    supply: "25/25",
    culturalMeaning: "Represents the continuity of history and royal authority.",
    spirit: "History Keeper",
    element: "Earth",
    island: "Kalimantan",
    openseaUrl: getOpenSeaUrl("29")
  },
  {
    id: "30",
    name: "Royal Raccoon",
    region: "Tidung",
    outfit: "Adat Tidung",
    rarity: "Common",
    image: `https://picsum.photos/seed/tidung-adat/800/1000`,
    lore: "A coastal blend of Malay and local Tidung styles. It is practical for the lifestyle of a citizen who lives between the tide and the shore.",
    ability: "Tidal Step: Can walk across water surfaces for short durations.",
    rarityReason: "Distinctive identity of the far northern border people.",
    price: "0.9",
    supply: "100/100",
    culturalMeaning: "Reflects the unique border identity and maritime adaptability.",
    spirit: "Border Wave",
    element: "Water",
    island: "Kalimantan",
    openseaUrl: getOpenSeaUrl("30")
  },

  // Sulawesi
  {
    id: "31",
    name: "Royal Raccoon",
    region: "Bugis",
    outfit: "Baju Bodo",
    rarity: "Epic",
    image: `https://picsum.photos/seed/bugis-bodo/800/1000`,
    lore: "The transparent 'short garment' whose color reveals the wearer's age and rank. It is a code of honor worn proudly on the high seas.",
    ability: "Gale Burst: Launches a powerful air wave that pushes back all enemies.",
    rarityReason: "One of the oldest documented forms of fashion in the archipelago.",
    price: "5.5",
    supply: "20/20",
    culturalMeaning: "Symbolizes the pride, status, and maritime bravery of the Bugis people.",
    spirit: "Bravery's Sail",
    element: "Air",
    island: "Sulawesi",
    openseaUrl: getOpenSeaUrl("31")
  },
  {
    id: "32",
    name: "Royal Raccoon",
    region: "Makassar",
    outfit: "Baju Labbu",
    rarity: "Rare",
    image: `https://picsum.photos/seed/makassar-labbu/800/1000`,
    lore: "The longer, more conservative cousin of the Bodo. It reflects the deep integration of belief and tradition in the great port of Makassar.",
    ability: "Port Wall: Creates a static zone where no enemies can accelerate.",
    rarityReason: "Specific refined variant used by the merchants of the southern ports.",
    price: "2.9",
    supply: "40/40",
    culturalMeaning: "Represents the disciplined and deep-rooted nature of cultural beliefs.",
    spirit: "Port Sentinel",
    element: "Water",
    island: "Sulawesi",
    openseaUrl: getOpenSeaUrl("32")
  },
  {
    id: "33",
    name: "Royal Raccoon",
    region: "Toraja",
    outfit: "Seppa Tallung Buku",
    rarity: "Legendary",
    image: `https://picsum.photos/seed/toraja-seppa/800/1000`,
    lore: "Reserved for the grandest funerals of the mists. It is the armor for a transition between worlds, where the soul meets the ancestors.",
    ability: "Spirit Bridge: Can summon a temporary ghostly ally to assist in combat.",
    rarityReason: "Requires specific approval and massive ceremonial context to wear.",
    price: "15.0",
    supply: "5/5",
    culturalMeaning: "Reflects the Torajan obsession with life, death, and the eternal journey.",
    spirit: "Spirit Guide",
    element: "Void",
    island: "Sulawesi",
    openseaUrl: getOpenSeaUrl("33")
  },
  {
    id: "34",
    name: "Royal Raccoon",
    region: "Minahasa",
    outfit: "Laku Tepu",
    rarity: "Rare",
    image: `https://picsum.photos/seed/minahasa-lakutepu/800/1000`,
    lore: "Brightly colored and full of life. It reflects the energetic and vibrant soul of the northern tip of Sulawesi.",
    ability: "Spark Flash: Emits a sudden flash that reveals all hidden traps and units.",
    rarityReason: "Distinctive northern aesthetic and festive tradition.",
    price: "2.2",
    supply: "45/45",
    culturalMeaning: "Symbolizes the joy, community, and energy of the northern people.",
    spirit: "Northern Spark",
    element: "Light",
    island: "Sulawesi",
    openseaUrl: getOpenSeaUrl("34")
  },
  {
    id: "35",
    name: "Royal Raccoon",
    region: "Gorontalo",
    outfit: "Biliu",
    rarity: "Epic",
    image: `https://picsum.photos/seed/gorontalo-biliu/800/1000`,
    lore: "A costume of purity and high marriage. It is intended to shield the bride like a precious jewel, protected by tradition and family.",
    ability: "Purity Aegis: Creates an area where no poison or environmental damage can affect allies.",
    rarityReason: "Extensive weight of ornaments and high-grade silk use.",
    price: "5.0",
    supply: "18/18",
    culturalMeaning: "Represents the sanctity of new beginnings and the purity of intent.",
    spirit: "Pure Shield",
    element: "Light",
    island: "Sulawesi",
    openseaUrl: getOpenSeaUrl("35")
  },
  {
    id: "36",
    name: "Royal Raccoon",
    region: "Tolaki",
    outfit: "Kinawo",
    rarity: "Rare",
    image: `https://picsum.photos/seed/tolaki-kinawo/800/1000`,
    lore: "Woven from nature itself. It is the living weight of the earth, using leaves and fibers to create a costume that breathes with the forest.",
    ability: "Bark Skin: Temporarily doubles the wearer's defensive stats.",
    rarityReason: "Extremely rare natural weaving skill required.",
    price: "3.8",
    supply: "25/25",
    culturalMeaning: "Emphasizes the deep bond between the Tolaki people and their ancestral lands.",
    spirit: "Earth Breathing",
    element: "Earth",
    island: "Sulawesi",
    openseaUrl: getOpenSeaUrl("36")
  },

  // Maluku & Papua
  {
    id: "37",
    name: "Royal Raccoon",
    region: "Ambon",
    outfit: "Baju Cele",
    rarity: "Common",
    image: `https://picsum.photos/seed/ambon-cele/800/1000`,
    lore: "The iconic red checked pattern of the Spice Islands. Simple, effective, and full of historical memories of the world-altering trade era.",
    ability: "Spice Scent: Can put enemies within a small radius into a deep sleep.",
    rarityReason: "The most iconic and persistent identity of the Moluccan people.",
    price: "0.6",
    supply: "100/100",
    culturalMeaning: "Reflects the resilient and festive spirit of the islands.",
    spirit: "Island Memory",
    element: "Air",
    island: "Maluku",
    openseaUrl: getOpenSeaUrl("37")
  },
  {
    id: "38",
    name: "Royal Raccoon",
    region: "Ternate",
    outfit: "Manteren Lamo",
    rarity: "Epic",
    image: `https://picsum.photos/seed/ternate-manteren/800/1000`,
    lore: "The majestic attire of the Sultanate of Ternate. It carries the authority of the spice-lords who once controlled the wealth of the East.",
    ability: "Sultan's Authority: Can force an enemy to retreat from an area for 30 seconds.",
    rarityReason: "The rare official costume of one of the great regional sultanates.",
    price: "6.0",
    supply: "15/15",
    culturalMeaning: "Represents the peak of power and historical influence in the East.",
    spirit: "Eastern Sovereign",
    element: "Void",
    island: "Maluku",
    openseaUrl: getOpenSeaUrl("38")
  },
  {
    id: "39",
    name: "Royal Raccoon",
    region: "Dani",
    outfit: "Koteka",
    rarity: "Legendary",
    image: `https://picsum.photos/seed/dani-koteka/800/1000`,
    lore: "The ultimate cultural icon. Stripped of all unnecessary weight, it is the purest expression of freedom and identity in the misty Baliem valley.",
    ability: "Valley Leap: Can jump across massive mountain ravines with single bounds.",
    rarityReason: "The highest symbol of Papuan identity recognized globally.",
    price: "18.0",
    supply: "5/5",
    culturalMeaning: "The embodiment of human pride and total connection to the earth.",
    spirit: "Valley King",
    element: "Fire",
    island: "Papua",
    openseaUrl: getOpenSeaUrl("39")
  },
  {
    id: "40",
    name: "Royal Raccoon",
    region: "Asmat",
    outfit: "Rok Rumbai",
    rarity: "Legendary",
    image: `https://picsum.photos/seed/asmat-rumbai/800/1000`,
    lore: "A costume woven from the swamp fibers and spirit-blessed wood. It is worn for the most profound rituals where man becomes wood and wood becomes ghost.",
    ability: "Swamp Ghost: Can move through any obstacle as if it were water.",
    rarityReason: "Deep spiritual connection to the Asmat wood-carving spirit world.",
    price: "16.5",
    supply: "8/8",
    culturalMeaning: "Reflects the Asmat belief that human life and nature are one.",
    spirit: "Wood Spirit",
    element: "Water",
    island: "Papua",
    openseaUrl: getOpenSeaUrl("40")
  },
  {
    id: "41",
    name: "Royal Raccoon",
    region: "Arfak",
    outfit: "Ewer",
    rarity: "Rare",
    image: `https://picsum.photos/seed/arfak-ewer/800/1000`,
    lore: "Decorated with the feathers of the birds of paradise. It represents the height of beauty in the dense mountain rain forests.",
    ability: "Feather Flight: Can glide through the air for extended distances.",
    rarityReason: "Extensive use of rare natural feathers and forest materials.",
    price: "3.5",
    supply: "25/25",
    culturalMeaning: "Symbolizes the connection to the celestial birds of the forest.",
    spirit: "Celestial Wing",
    element: "Air",
    island: "Papua",
    openseaUrl: getOpenSeaUrl("41")
  },
  {
    id: "42",
    name: "Royal Raccoon",
    region: "Biak",
    outfit: "Adat Biak",
    rarity: "Common",
    image: `https://picsum.photos/seed/biak-adat/800/1000`,
    lore: "The costume of the dancing mariners. It is full of movement and life, designed for the rapid rhythm of the coastal waves.",
    ability: "Wave Dance: Dodge chance increases by 50% for 10 seconds.",
    rarityReason: "The widely recognized traditional identity of the Biak people.",
    price: "0.7",
    supply: "100/100",
    culturalMeaning: "Represents the energetic and maritime nature of the islanders.",
    spirit: "Wave Dancer",
    element: "Water",
    island: "Papua",
    openseaUrl: getOpenSeaUrl("42")
  }
];

export const RARITIES = [
  { name: "Common", color: "text-gray-400", glow: "shadow-gray-900/20", aura: "from-gray-500/10 to-transparent", desc: "The balanced guardians of the realm." },
  { name: "Rare", color: "text-blue-400", glow: "shadow-blue-500/20", aura: "from-blue-500/20 to-transparent", desc: "Awakened spirits with ancient wisdom." },
  { name: "Epic", color: "text-purple-400", glow: "shadow-purple-500/20", aura: "from-purple-500/20 to-transparent", desc: "Masters of the hidden elements." },
  { name: "Legendary", color: "text-yellow-400", glow: "shadow-yellow-500/30", aura: "from-yellow-400/20 to-transparent", desc: "Mythical kings of a forgotten era." },
  { name: "Mythic", color: "text-red-500", glow: "shadow-red-500/30", aura: "from-red-500/20 to-transparent", desc: "Transcendent beings beyond time." },
  { name: "Divine", color: "text-white", glow: "shadow-white/40", aura: "from-white/20 to-transparent", desc: "The supreme architects of Nusantara." }
];

export const ROADMAP = [
  { phase: "01", title: "The Awakening", date: "Q2 2026", items: ["Launch 10 Origin NFTs", "Website V1 release", "Community building"] },
  { phase: "02", title: "Cultural Expansion", date: "Q3 2026", items: ["Expand to 100 Unique NFTs", "Lore storytelling V1", "Staking launch"] },
  { phase: "03", title: "Nusantara Lore", date: "Q4 2026", items: ["Story expansions", "Exclusive member events", "Airdrop for holders"] },
  { phase: "04", title: "The Metaverse", date: "2027", items: ["Metaverse integration", "Royal Beast 3D avatars", "The Kingdom RPG"] }
];
